#pragma once

enum class ValidationError {
    NONE,
    TOO_SMALL_FOR_ETHERNET,
    TOO_SMALL_FOR_IPV4,
    INVALID_IPV4_IHL,
    IPV4_TOTAL_LENGTH_TOO_SMALL,
    IPV4_TOTAL_LENGTH_TOO_LARGE,
    TOO_SMALL_FOR_TCP,
    INVALID_TCP_HEADER_SIZE,
    TOO_SMALL_FOR_UDP,
    INVALID_UDP_LENGTH,
    UNSUPPORTED_L4_PROTOCOL
};



