#pragma once

enum class ValidationError {
    NONE,
    TOO_SMALL_FOR_ETHERNET,
    INVALID_ETHERTYPE,
    MISSING_IPV4_HEADER,
    TOO_SMALL_FOR_IPV4,
    INVALID_IPV4_VERSION,
    INVALID_IPV4_IHL,
    INVALID_IPV4_IHL_LENGTH,
    INVALID_IPV4_TOTAL_LENGTH,
    IPV4_TOTAL_LENGTH_EXCEEDS_PACKET,
    MISSING_TCP_HEADER,
    TOO_SMALL_FOR_TCP,
    INVALID_TCP_DATA_OFFSET,
    TCP_HEADER_EXCEEDS_PACKET,
    MISSING_UDP_HEADER,
    TOO_SMALL_FOR_UDP,
    INVALID_UDP_LENGTH,
    UDP_LENGTH_EXCEEDS_PACKET,    
    UNSUPPORTED_L4_PROTOCOL
};



