#pragma once
#include <string>


namespace dp {
namespace validation {

// Supported Validation Errors
enum class ValidationError {
    NONE,
    // Ethernet
    TOO_SMALL_FOR_ETHERNET,
    INVALID_ETHERTYPE,
    // arp
    ARP_TRUNCATED_HEADER,
    ARP_INVALID_HTYPE,
    ARP_INVALID_PTYPE,
    ARP_INVALID_HLEN,
    ARP_INVALID_PLEN,
    ARP_INVALID_OPCODE,
    ARP_TRUNCATED_ADDRESSES,
    ARP_REPLY_TO_BROADCAST,
    // icmp 
    MISSING_ICMP_HEADER,
    TOO_SMALL_FOR_ICMP,
    ICMP_INVALID_TYPE,
    ICMP_INVALID_CODE,
    ICMP_INVALID_CHECKSUM,
    ICMP_TRUNCATED_PAYLOAD,
    ICMP_EMBEDDED_IPV4_INVALID,
    // ipv4
    MISSING_IPV4_HEADER,
    TOO_SMALL_FOR_IPV4,
    INVALID_IPV4_VERSION,
    INVALID_IPV4_IHL,
    INVALID_IPV4_IHL_LENGTH,
    INVALID_IPV4_TOTAL_LENGTH,
    IPV4_TOTAL_LENGTH_EXCEEDS_PACKET,
    IPV4_INVALID_CHECKSUM,
    // tcp
    MISSING_TCP_HEADER,
    TOO_SMALL_FOR_TCP,
    INVALID_TCP_DATA_OFFSET,
    TCP_HEADER_EXCEEDS_PACKET,
    TCP_INVALID_CHECKSUM,
    //udp
    MISSING_UDP_HEADER,
    TOO_SMALL_FOR_UDP,
    INVALID_UDP_LENGTH,
    UDP_LENGTH_EXCEEDS_PACKET,
    UDP_INVALID_CHECKSUM,
    // Miscellaneous    
    UNSUPPORTED_L4_PROTOCOL
};


std::string to_string(ValidationError err);


} // namespace validation
} // namespace dp


