#pragma once
#include <string>


namespace dp {
namespace validation {

// Supported Validation Errors
enum class ValidationError {
    NONE,
    // Ethernet
    TOO_SMALL_FOR_ETHERNET,
    INVALID_ETHERTYPE,
    // arp
    ARP_TRUNCATED_HEADER,
    ARP_INVALID_HTYPE,
    ARP_INVALID_PTYPE,
    ARP_INVALID_HLEN,
    ARP_INVALID_PLEN,
    ARP_INVALID_OPCODE,
    ARP_TRUNCATED_ADDRESSES,
    ARP_REPLY_TO_BROADCAST,
    // icmpv4 
    MISSING_ICMPV4_HEADER,
    TOO_SMALL_FOR_ICMPV4,
    ICMPV4_INVALID_TYPE,
    ICMPV4_INVALID_CODE,
    ICMPV4_INVALID_CHECKSUM,
    ICMPV4_TRUNCATED_PAYLOAD,
    ICMPV4_EMBEDDED_IPV4_INVALID,
    // ipv4
    MISSING_IPV4_HEADER,
    TOO_SMALL_FOR_IPV4,
    INVALID_IPV4_VERSION,
    INVALID_IPV4_IHL,
    INVALID_IPV4_IHL_LENGTH,
    INVALID_IPV4_TOTAL_LENGTH,
    IPV4_TOTAL_LENGTH_EXCEEDS_PACKET,
    IPV4_INVALID_CHECKSUM,
    IPV4_OPTIONS_TRUNCATED,
    IPV4_FRAGMENT_OFFSET_INVALID,
    IPV4_MORE_FRAGMENTS_INVALID,
    // ipv6
    MISSING_IPV6_HEADER,
    TOO_SMALL_FOR_IPV6,
    INVALID_IPV6_VERSION,
    INVALID_IPV6_PAYLOAD_LENGTH,
    IPV6_PAYLOAD_EXCEEDS_PACKET,
    IPV6_UNSUPPORTED_NEXT_HEADER,
    IPV6_HOP_LIMIT_ZERO,
    IPV6_EXTENSION_HEADER_PRESENT,
    IPV6_EXTENSION_HEADER_UNSUPPORTED,
    IPV6_EXTENSION_HEADER_TRUNCATED,
    // icmpv6
    ICMPV6_MISSING_HEADER,
    ICMPV6_TOO_SMALL,
    ICMPV6_INVALID_TYPE,
    ICMPV6_INVALID_CODE,
    ICMPV6_INVALID_CHECKSUM,
    ICMPV6_TRUNCATED_PAYLOAD,
    ICMPV6_EMBEDDED_IPV6_INVALID,
    ICMPV6_ERROR_MESSAGE_INVALID,
    // tcp
    MISSING_TCP_HEADER,
    TOO_SMALL_FOR_TCP,
    INVALID_TCP_DATA_OFFSET,
    TCP_HEADER_EXCEEDS_PACKET,
    TCP_INVALID_CHECKSUM,
    //udp
    MISSING_UDP_HEADER,
    TOO_SMALL_FOR_UDP,
    INVALID_UDP_LENGTH,
    UDP_LENGTH_EXCEEDS_PACKET,
    UDP_INVALID_CHECKSUM,
    // Miscellaneous    
    UNSUPPORTED_IP_PROTOCOL
};


std::string to_string(ValidationError err);


} // namespace validation
} // namespace dp


